name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up variables
      id: vars
      run: |
        echo "VERSION=$(($(cat version.txt) + 1))" >> $GITHUB_ENV
        echo "DOCKER_TAG=deepanshu461/sampleimage:${{ env.VERSION }}" >> $GITHUB_ENV

    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERPWD }}" | docker login -u "deepanshu461" --password-stdin
        docker image build -t "${{ env.DOCKER_TAG }}" .
        docker push "${{ env.DOCKER_TAG }}"
      
    - name: Update version
      run: echo "${{ env.VERSION }}" > version.txt
