name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Increment Version
      id: increment_version
      run: echo $(( $(cat version.txt) + 1 )) > version.txt
      
    - name: Set Version
      id: set_version
      run: echo "::set-output name=version::$(cat version.txt)"
      
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERPWD }}" | docker login -u "deepanshu461" --password-stdin
        docker image build -t deepanshu461/sampleimage:${{ steps.set_version.outputs.version }} .
        docker push deepanshu461/sampleimage:${{ steps.set_version.outputs.version }}
